# -*- coding: utf-8 -*-
"""FPGA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jiDw4oZMA0VpSoIg8NNkVXjin4OvSQG8
"""

from google.colab import files
files.upload()  # Upload kaggle.json here

import os

!mkdir -p ~/.kaggle
!mv kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d ryanmouton/ohiot1dm

!unzip ohiot1dm.zip

import xml.etree.ElementTree as ET
import glob
import os

# If files are uploaded directly, they will be in current directory
xml_files = glob.glob("*.xml")

print(f"Found {len(xml_files)} XML files\n")

results = []

for file in xml_files:
    tree = ET.parse(file)
    root = tree.getroot()

    patient_id = root.attrib.get("id", "Unknown")

    glucose_values = []

    glucose_section = root.find("glucose_level")

    if glucose_section is not None:
        for event in glucose_section:
            value = int(event.attrib["value"])
            glucose_values.append(value)

    if len(glucose_values) > 0:
        min_val = min(glucose_values)
        max_val = max(glucose_values)

        print(f"Patient {patient_id}:")
        print(f"   Min Glucose = {min_val} mg/dL")
        print(f"   Max Glucose = {max_val} mg/dL\n")

        results.append((patient_id, min_val, max_val))
    else:
        print(f"Patient {patient_id}: No glucose data found\n")

import xml.etree.ElementTree as ET
import glob

xml_files = glob.glob("*.xml")

total_samples = 0
hypo_samples = 0

for file in xml_files:
    tree = ET.parse(file)
    root = tree.getroot()

    glucose_section = root.find("glucose_level")

    if glucose_section is not None:
        for event in glucose_section:
            value = int(event.attrib["value"])

            total_samples += 1

            if value < 70:
                hypo_samples += 1

print("===== DATASET STATISTICS =====")
print(f"Total Glucose Samples: {total_samples}")
print(f"Hypoglycemia Samples (<70 mg/dL): {hypo_samples}")

percentage = (hypo_samples / total_samples) * 100
print(f"Hypoglycemia Percentage: {percentage:.2f}%")

import xml.etree.ElementTree as ET
import glob
import numpy as np

# --------------------------
# CONFIG
WINDOW = 12      # 1-hour history (12 samples)
HORIZON = 6      # 30 min ahead prediction
HYPO_THRESHOLD = 70  # mg/dL
TARGET_RATIO = 10    # majority : minority ratio
# --------------------------

xml_files = glob.glob("*.xml")
all_series = []

# ---- Extract all glucose values from XML files ----
for file in xml_files:
    tree = ET.parse(file)
    root = tree.getroot()
    glucose_section = root.find("glucose_level")

    if glucose_section is not None:
        series = []
        for event in glucose_section:
            try:
                value = int(event.attrib["value"])
                series.append(value)
            except (ValueError, KeyError):
                continue  # skip invalid entries
        if len(series) >= WINDOW + HORIZON:
            all_series.append(series)

print(f"Total series loaded: {len(all_series)}")

# ---- Create sliding windows + labels ----
X = []
Y = []

for series in all_series:
    for i in range(WINDOW, len(series) - HORIZON):
        window = series[i-WINDOW:i]
        future_value = series[i+HORIZON]
        label = 1 if future_value < HYPO_THRESHOLD else 0
        X.append(window)
        Y.append(label)

X = np.array(X)
Y = np.array(Y)

print("Original dataset shape:")
print("X:", X.shape)
print("Y:", Y.shape)
print(f"Hypoglycemia percentage: {np.mean(Y)*100:.2f}%")
print(f"Hypoglycemia samples: {np.sum(Y)}")
print(f"Normal samples: {len(Y) - np.sum(Y)}")

# ---- Separate majority and minority classes ----
X_min = X[Y==1]
Y_min = Y[Y==1]
X_maj = X[Y==0]
Y_maj = Y[Y==0]

# ---- Oversample minority class to achieve TARGET_RATIO ----
n_maj = len(Y_maj)
n_min_target = n_maj // TARGET_RATIO
n_repeat = n_min_target // len(Y_min)
n_extra = n_min_target - n_repeat * len(Y_min)

# Duplicate minority windows
X_min_oversampled = np.tile(X_min, (n_repeat, 1))
Y_min_oversampled = np.tile(Y_min, n_repeat)

# Add remaining random samples if needed
if n_extra > 0:
    extra_idx = np.random.choice(len(Y_min), n_extra, replace=True)
    X_min_oversampled = np.vstack([X_min_oversampled, X_min[extra_idx]])
    Y_min_oversampled = np.hstack([Y_min_oversampled, Y_min[extra_idx]])

# ---- Combine majority + oversampled minority ----
X_balanced = np.vstack([X_maj, X_min_oversampled])
Y_balanced = np.hstack([Y_maj, Y_min_oversampled])

# ---- Shuffle the dataset ----
shuffle_idx = np.random.permutation(len(Y_balanced))
X_balanced = X_balanced[shuffle_idx]
Y_balanced = Y_balanced[shuffle_idx]

# ---- Dataset statistics after balancing ----
hypo_count = np.sum(Y_balanced)
normal_count = len(Y_balanced) - hypo_count

print("\nBalanced dataset:")
print("X_balanced:", X_balanced.shape)
print("Y_balanced:", Y_balanced.shape)
print(f"Hypoglycemia samples: {hypo_count}")
print(f"Normal samples: {normal_count}")
print(f"Hypoglycemia percentage: {hypo_count/len(Y_balanced)*100:.2f}%")
print(f"Final majority:minority ratio: {normal_count/hypo_count:.2f}")

# ---- Save to npy files for later training or mem export ----
np.save("X_balanced.npy", X_balanced)
np.save("Y_balanced.npy", Y_balanced)

print("\nBalanced dataset saved to X_balanced.npy and Y_balanced.npy")

X_balanced = X_balanced / 400.0   # since max glucose ~400
X.shape

assert X_balanced.shape[0] == Y_balanced.shape[0], "X and Y must have same number of samples"

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_balanced, Y_balanced, test_size=0.2, random_state=42, stratify=Y_balanced
)

print("Train:", X_train.shape)
print("Test:", X_test.shape)

import pandas as pd

print("Train class distribution:")
print(pd.Series(y_train).value_counts(normalize=True))

print("\nTest class distribution:")
print(pd.Series(y_test).value_counts(normalize=True))

np.save("X_test.npy", X_test)
np.save("y_test.npy", y_test)

from sklearn.utils.class_weight import compute_class_weight
import numpy as np

classes = np.array([0,1])

weights = compute_class_weight(
    class_weight='balanced',
    classes=classes,
    y=y_train
)

class_weights = {0: weights[0], 1: weights[1]}

print(class_weights)

import tensorflow as tf
from tensorflow.keras import layers, models

model = models.Sequential([
    layers.Input(shape=(12,1)),

    layers.Conv1D(8, kernel_size=3, padding='same'),
    layers.ReLU(),
    layers.MaxPooling1D(2),

    layers.Conv1D(16, kernel_size=3, padding='same'),
    layers.ReLU(),
    layers.GlobalAveragePooling1D(),

    layers.Dense(2)
])

model.compile(
    optimizer='adam',
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics=['accuracy']
)

model.summary()

X_train = X_train.reshape(-1,12,1)
X_test  = X_test.reshape(-1,12,1)

history = model.fit(
    X_train, y_train,
    epochs=15,
    batch_size=128,
    validation_data=(X_test, y_test),
    class_weight=class_weights
)

import numpy as np
from sklearn.metrics import classification_report

# Get probabilities
logits = model.predict(X_test)
probs = tf.nn.softmax(logits).numpy()

# Change threshold
threshold = 0.7   # try 0.6, 0.7, 0.8

y_pred = (probs[:,1] > threshold).astype(int)

print(classification_report(y_test, y_pred))

import numpy as np

class0_idx = np.where(y_test == 0)[0]
class1_idx = np.where(y_test == 1)[0]

n = min(len(class1_idx), 1000)

idx0 = np.random.choice(class0_idx, n, replace=False)
idx1 = np.random.choice(class1_idx, n, replace=False)

balanced_idx = np.concatenate([idx0, idx1])

X_bal = X_test[balanced_idx]
y_bal = y_test[balanced_idx]

X_bal.shape
y_bal.shape

import tensorflow as tf

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]

def representative_data_gen():
    for i in range(1000):
        yield [X_train[i:i+1].astype(np.float32)]

converter.representative_dataset = representative_data_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8
converter.inference_output_type = tf.int8

tflite_model = converter.convert()

with open("model_int8.tflite", "wb") as f:
    f.write(tflite_model)

print("INT8 model generated.")

import numpy as np
import tensorflow as tf
from sklearn.metrics import classification_report

# Load INT8 model
interpreter = tf.lite.Interpreter(model_path="model_int8.tflite")
interpreter.allocate_tensors()

input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Get scale and zero-point
input_scale, input_zero = input_details[0]['quantization']
output_scale, output_zero = output_details[0]['quantization']

threshold = 0.7   # try 0.6, 0.7, 0.8

y_pred = []

for i in range(len(X_test)):

    x = X_test[i:i+1]
    x_int8 = (x / input_scale + input_zero).astype(np.int8)

    interpreter.set_tensor(input_details[0]['index'], x_int8)
    interpreter.invoke()

    output = interpreter.get_tensor(output_details[0]['index'])
    output_float = (output.astype(np.float32) - output_zero) * output_scale

    # Softmax
    probs = tf.nn.softmax(output_float).numpy()

    pred = 1 if probs[0][1] > threshold else 0
    y_pred.append(pred)

y_pred = np.array(y_pred)

print(classification_report(y_test, y_pred))

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_data_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8
converter.inference_output_type = tf.int8

tflite_model = converter.convert()

with open("model_int8.tflite", "wb") as f:
    f.write(tflite_model)

import numpy as np
import tensorflow as tf

interpreter = tf.lite.Interpreter(model_path="model_int8.tflite")
interpreter.allocate_tensors()

tensor_details = interpreter.get_tensor_details()
for tensor in interpreter.get_tensor_details():
    print(tensor["index"], tensor["name"], tensor["shape"])

for tensor in tensor_details:
    if "kernel" in tensor["name"] or "weight" in tensor["name"]:
        weights = interpreter.get_tensor(tensor["index"])
        print(tensor["name"], weights.shape)

np.savetxt("conv1_weights.txt", weights.flatten(), fmt="%d")

import numpy as np

def save_tensor(idx, name):
    tensor = interpreter.get_tensor(idx)
    print(name, tensor.shape)
    print("Min/Max:", tensor.min(), tensor.max())
    np.savetxt(name + ".mem", tensor.flatten(), fmt="%d")

save_tensor(11, "conv1_weights")
save_tensor(10, "conv1_bias")

save_tensor(9, "conv2_weights")
save_tensor(8, "conv2_bias")

save_tensor(7, "dense_weights")
save_tensor(6, "dense_bias")

for tensor in interpreter.get_tensor_details():
    qp = tensor["quantization_parameters"]
    if len(qp["scales"]) > 0:
        print(tensor["name"])
        print("Scale:", qp["scales"])
        print("Zero Point:", qp["zero_points"])

import tensorflow as tf
import datetime

log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

tensorboard_callback = tf.keras.callbacks.TensorBoard(
    log_dir=log_dir,
    histogram_freq=1,
    write_graph=True
)

!pip install pydot graphviz

from tensorflow.keras.utils import plot_model

plot_model(model,
           to_file='model.png',
           show_shapes=True,
           show_layer_names=True)

from tensorflow.keras.utils import plot_model

plot_model(
    model,
    to_file="model_visual.png",
    show_shapes=True,
    show_layer_names=True,
    show_layer_activations=True,
    rankdir="TB",      # TB = top-bottom, LR = left-right
    dpi=200,           # higher resolution
    expand_nested=True
)

pip install visualkeras

model.build(input_shape=(None, 12, 1))  # (batch, timesteps, channels)

import visualkeras
from PIL import ImageFont



visualkeras.layered_view(
    model,
    legend=True,
    to_file="model_3d.png"
)

